[phases.setup]
nixPkgs = ['python311', 'gcc', 'curl']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase - nothing to build"']

[start]
cmd = 'uvicorn api:app --host 0.0.0.0 --port $PORT'
