[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "always"

# Configurações específicas para Railway
[build.args]
BUILDKIT_INLINE_CACHE = "1"

# Notas:
# - builder = "dockerfile" força o uso do Dockerfile
# - healthcheckPath usa /healthz (endpoint leve)
# - restartPolicyType = "always" para reinicialização automática
# - CMD do Dockerfile agora usa ./start.sh para lidar com PORT corretamente
