[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 120
restartPolicyType = "always"

# Notas:
# - healthcheckPath agora usa /healthz (leve e rápido)
# - Porta exposta configurada no Dockerfile (8000) e sobrescrita via env PORT
